esc="\033"
ss2="N"     # Single Shift Two
ss3="O"     # Single Shift Three
dcs="P"     # Device Control String
sos="X"     # Start of String
ris="c"     # Reset to Initial State
csi="["     # Control Sequence Indroducer
st="\\"     # String Terminator
osc="]"     # Operating System Command
pm="^"      # Privacy Message
apc="_"     # Application Program Command

# ------------ CSI ------------ #
csi_cuu="A"     # Cursor Up
csi_cud="B"     # Cursor Down
csi_cuf="C"     # Cursor Forward
csi_cub="D"     # Cursor Back
csi_cnl="E"     # Cursor Next Line
csi_cpl="F"     # Cursor Previous Line
csi_cha="G"     # Cursor Horizontal Absolute
csi_cup="H"     # Cursor Position
csi_ed="J"      # Erase in Display
csi_el="K"      # Erase in Line
csi_su="S"      # Scroll Up
csi_sd="T"      # Scroll Down
csi_hvp="f"     # Horizontal Vertical Position (eq to CUP)
csi_sgr="m"     # Select Graphic Rendition
csi_scp="s"     # Save Cursor Position
csi_rcp="u"     # Restore Cursor Position
csi_ap_on="4i"  # AUX Port On
csi_ap_off="5i" # AUX Port Off
csi_dsr="6n"    # Device Status Report
csi_sc="?25h"   # Show Cursor
csi_hc="?25l"   # Hide Cursor

ed_end_of_screen="0"
ed_beginning_of_screen="1"
ed_entire_screen="2"
ed_entire_screen_del_sb_buf="3"

el_end_of_line="0"
el_beginning_of_line="1"
el_entire_line="2"

sgr_reset="0"
sgr_bold="1"
sgr_half_bright="2"
sgr_italic="3"
sgr_underline="4"
sgr_blink="5"
sgr_rapid_blink="6"
sgr_reverse_video="7"
sgr_conceal="8"
sgr_crossed_out="9"
sgr_primary_font="10"
sgr_alternate_font_1="11"
sgr_alternate_font_2="12"
sgr_alternate_font_3="13"
sgr_alternate_font_4="14"
sgr_alternate_font_5="15"
sgr_alternate_font_6="16"
sgr_alternate_font_7="17"
sgr_alternate_font_8="18"
sgr_alternate_font_9="19"
sgr_fraktur="20"
sgr_bold_off="21"
sgr_normal_intensity="22"
sgr_italic_off_fraktur_off="23"
sgr_underline_off="24"
sgr_blink_off="25"
sgr_inverse_off="27"
sgr_reveal="28"
sgr_not_crossed_out="29"
sgr_fg_black="30"
sgr_fg_red="31"
sgr_fg_green="32"
sgr_fg_yellow="33"
sgr_fg_blue="34"
sgr_fg_magenta="35"
sgr_fg_cyan="36"
sgr_fg_white="37"
sgr_set_fg_color_rgb="38;2"
sgr_set_fg_color_list="38;5"
sgr_default_fg_color="39"
sgr_bg_black="40"
sgr_bg_red="41"
sgr_bg_green="42"
sgr_bg_yellow="43"
sgr_bg_blue="44"
sgr_bg_magenta="45"
sgr_bg_cyan="46"
sgr_bg_white="47"
sgr_set_bg_color_rgb="48;2"
sgr_set_bg_color_list="48;5"
sgr_default_bg_color="49"
sgr_framed="51"
sgr_encircled="52"
sgr_overlined="53"
sgr_frame_off_encircle_off="54"
sgr_overline_off="55"
sgr_ideogram_underline="60"
sgr_ideogram_double_underline="61"
sgr_ideogram_overline="62"
sgr_ideogram_double_overline="63"
sgr_ideogram_stress_marking="64"
sgr_ideogram_attributes_off="65"

osc_set_icon_title="0;"
osc_set_icon="1;"
osc_set_title="2;"
